### ISSUE TITLE
Copy and paste umlauts does not work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [douglasdrumond/macvim#527]
```
When I copy a text which includes umlauts from Preview to MacVim all umlauts 
are broken.

I can't reproduce this with the Vim version included in OSX Yosemite (which is 
Vim 7.3), using the default Terminal.app

MacVim 7.4 (73) with 7.4.540
OSX Yosemite 10.10.2
```

Original issue reported on code.google.com by `thbohn` on 2 Feb 2015 at 4:52

Attachments:
* [Screen Shot 2015-02-02 at 05.49.29.png](https://storage.googleapis.com/google-code-attachments/macvim/issue-527/comment-0/Screen Shot 2015-02-02 at 05.49.29.png)

**Comment by douglasdrumond** [comment]
This issue was moved to macvim-dev/macvim#27
