### ISSUE TITLE
Settings belong under MacVim menu, not Edit

### ISSUE THREAD

**Issue by GoogleCodeExporter** [douglasdrumond/macvim#529]
```
Version: Snapshot 74

Currently, the menu items for editing various settings (except those in the 
Preferences panel) are found under the Edit menu. This is the wrong location, 
and goes against Mac design patterns. Edit is for commands that edit or 
interact with text, not for editing preferences.

Atom and Sublime Text have similar approaches, and I suggest adopting the one 
Atom uses. That is, move all of the setting-related menu items directly beneath 
Preferences in the MacVim menu.

The items that should be moved:
Settings Window (suggested rename: Available Settings)
Startup Settings
Global Settings
File Settings
Color Scheme
Keymap

As a side note, when all windows are minimized, Startup Window and Startup 
Settings are greyed out. That is likely a bug.
```

Original issue reported on code.google.com by `peterjel...@gmail.com` on 5 Mar 2015 at 1:31

Attachments:
* [Screen Shot 2015-03-04 at 5.17.41 PM.png](https://storage.googleapis.com/google-code-attachments/macvim/issue-529/comment-0/Screen Shot 2015-03-04 at 5.17.41 PM.png)
* [Screen Shot 2015-03-04 at 5.16.14 PM.png](https://storage.googleapis.com/google-code-attachments/macvim/issue-529/comment-0/Screen Shot 2015-03-04 at 5.16.14 PM.png)
* [Screen Shot 2015-03-04 at 5.16.34 PM.png](https://storage.googleapis.com/google-code-attachments/macvim/issue-529/comment-0/Screen Shot 2015-03-04 at 5.16.34 PM.png)

**Comment by douglasdrumond** [comment]
This issue was moved to macvim-dev/macvim#25
